---
# ansible_architecture = 32-bit(?) | 64-bit
windows_arch: "{{ ansible_architecture | split('-') | first }}"

zabbix_win_download_url: https://cdn.zabbix.com/zabbix/binaries/stable
zabbix_win_install_dir: 'C:\Zabbix'

zabbix_win_package: zabbix_agent-{{ zabbix_version }}-windows-amd64-openssl.zip
zabbix_win_download_link: "{{ zabbix_win_download_url }}/{{ zabbix_version | regex_search('^\\d+\\.\\d+') }}/{{ zabbix_version }}/{{ zabbix_win_package }}"
zabbix_win_exe_path: '{{ zabbix_win_install_dir }}\bin\zabbix_agentd.exe'
zabbix_win_svc_name: Zabbix Agent
zabbix_win_config_name: 'zabbix_agentd.conf'

zabbix2_win_package: zabbix_agent2-{{ zabbix_version }}-windows-amd64-openssl-static.zip
zabbix2_win_download_link: "{{ zabbix_win_download_url }}/{{ zabbix_version | regex_search('^\\d+\\.\\d+') }}/{{ zabbix_version }}/{{ zabbix2_win_package }}"
zabbix2_win_exe_path: '{{ zabbix_win_install_dir }}\bin\zabbix_agent2.exe'
zabbix2_win_svc_name: Zabbix Agent 2
zabbix2_win_config_name: 'zabbix_agent2.conf'

# zabbix_agent_win_logfile: "{{ zabbix_win_install_dir }}\\zabbix_agentd.log"
# zabbix_agent2_win_logfile: "{{ zabbix_win_install_dir }}\\zabbix_agent2.log"
# zabbix_agent_win_svc_recovery: true
# zabbix_win_firewall_management: true