---
ad:
  hosts:
    active:
      ansible_host: active.office.taxnet.ru
    bright:
      ansible_host: bright.office.taxnet.ru
    heaven:
      ansible_host: heaven.office.taxnet.ru

backup_db:
  hosts:
    rebacker:
      ansible_host: rebacker.office.taxnet.ru

file_storage:
  hosts:
    narnia:
      ansible_host: narnia.office.taxnet.ru

transcrypt_app:
  hosts:
    transcrypt_app_a:
      ansible_host: 172.24.10.53
    transcrypt_app_b:
      ansible_host: 172.24.10.122
  
iis:
  children:
    transcrypt_app:

transcrypt:
  children:
    iis:

# mssql:
#   children:
#     rebacker:

# infra:
#   children:
#     rebacker:
#     narnia:
#     ad:
#     mssql:

taxnet:
  children:
    ad:
    backup_db:
    iis:
    mssql:
    file_storage: