---
_1c_group:
  hosts:
    1c8:
      ansible_host: srv1cv8.office.taxnet.ru
    1csql:
      ansible_host: 1csql.office.taxnet.ru
    summer3:
      ansible_host: summer3.office.taxnet.ru

ad_group:
  hosts:
    active:
      ansible_host: active.office.taxnet.ru
    bright:
      ansible_host: bright.office.taxnet.ru
    heaven:
      ansible_host: heaven.office.taxnet.ru

backupdb_group:
  hosts:
    rebacker:
      ansible_host: rebacker.office.taxnet.ru

infra_group:
  hosts:
    narnia:
      ansible_host: narnia.office.taxnet.ru
    naumen:
      ansible_host: Naumen.office.taxnet.ru
    rdgw:
      ansible_host: rdgw.office.taxnet.ru
    sus:
      ansible_host: sus.office.taxnet.ru
  children:
    backupdb_group:

other_group:
  hosts:
    eufrat:
      ansible_host: eufrat.office.taxnet.ru

testenv_group:
  hosts:
    dpr_autotest:
      ansible_host: dpr-autotest.office.taxnet.ru

taxnet_nondomain:
  hosts:
    obfuscator:
  children:
    transcrypt:

taxnet_domain:
  children:
    _1c_group:
    ad_group:
    backupdb_group:
    cryptogramm:
    cryptxdss:
    declaration:
    identify_group:
    infra_group:
    oktell:
    other_group:
    testenv_group:
    tfs:
    tatenergosbyt:
    veeam:
    
disabled_hosts:
  hosts:
    veeam_kn:
    cryptogramm_gost:
    agn2:
    agnt1:
  children:
    identify_group:
    oktell:

taxnet:
  children:
    taxnet_domain:
    taxnet_nondomain:
    disabled_hosts: