---
servers_1c:
  hosts:
    1c8:
      ansible_host: srv1cv8.office.taxnet.ru
    1csql:
      ansible_host: 1csql.office.taxnet.ru
    summer3:
      ansible_host: summer3.office.taxnet.ru

ad:
  hosts:
    active:
      ansible_host: active.office.taxnet.ru
    bright:
      ansible_host: bright.office.taxnet.ru
    heaven:
      ansible_host: heaven.office.taxnet.ru

backup_db:
  hosts:
    rebacker:
      ansible_host: rebacker.office.taxnet.ru

cryptogramm_prod:
  hosts:
    cryptogramm_serv:
      ansible_host: cryptogramm.office.taxnet.ru
    cryptogramm_gost:
      ansible_host: cryptogramm-gost.office.taxnet.ru
    rostselmash:
      ansible_host: 172.24.10.139

cryptogramm_dev:
  hosts:
    cryptogramm_demo:
      ansible_host: cryptogramm-demo.office.taxnet.ru
    rostselmash_test:
      ansible_host: rostselmash-test.office.taxnet.ru

cryptogramm:
  children:
    cryptogramm_prod:
    cryptogramm_dev:

cryptxdss_prod:
  hosts:
    copykey2:
      ansible_host: copykey2.office.taxnet.ru
    dssclients_clone:
      ansible_host: dssclientsclone.office.taxnet.ru
    dsstaxnet:
      ansible_host: dssup.office.taxnet.ru

cryptxdss_dev:
  hosts:
    copykey:
      ansible_host: copykey.office.taxnet.ru
    dsstaxnet_test:
      ansible_host: dss-taxnet-test.office.taxnet.ru
    dsstest:
      ansible_host: dsstest.office.taxnet.ru

cryptxdss:
  children:
    cryptxdss_prod:
    cryptxdss_dev:

declaration:
  hosts:
    demoreferent:
      ansible_host:
    flc:
      ansible_host: demoreferent.office.taxnet.ru
    webreferent_app:
      ansible_host: flc.office.taxnet.ru
    webreferent_sql:
      ansible_host: webreferent-app.office.taxnet.ru

identify:
  hosts:
    identify2:
      ansible_host: 192.168.170.215
    identify2_test:
      ansible_host: 172.24.5.170

infra:
  hosts:
    narnia:
      ansible_host: narnia.office.taxnet.ru
    naumen:
      ansible_host: Naumen.office.taxnet.ru
    rdgw:
      ansible_host: rdgw.office.taxnet.ru
    sus:
      ansible_host: sus.office.taxnet.ru

oktell:
  hosts:
    oktell_serv:
      ansible_host: 91.224.52.9
    oktell_sql:
      ansible_host: oktell-sql.office.taxnet.ru

other:
  hosts:
    eufrat:
      ansible_host: 172.24.10.14

testenv:
  hosts:
    dpr_autotest:
      ansible_host: dpr-autotest.office.taxnet.ru

tfs:
  hosts:
    tfs_serv:
      ansible_host: tfs.office.taxnet.ru
    build_agent:
      ansible_host: dpr-build-agent.office.taxnet.ru
    obfuscator:
      ansible_host: 192.168.170.107

transcrypt_agn:
  hosts:
    agn1:
      ansible_host: 172.24.10.38

transcrypt_app:
  hosts:
    app_a:
      ansible_host: 172.24.10.53
    app_b:
      ansible_host: 172.24.10.122

transcrypt_pdf:
  hosts:
    pdf_a:
      ansible_host: 172.24.10.50
    pdf_b:
      ansible_host: 172.24.10.79

tatenergosbyt:
  hosts:
    tesb_eoks:
      ansible_host: tesb-eoks.office.taxnet.ru

transcrypt_prod:
  children:
    transcrypt_agn:
    transcrypt_app:
    transcrypt_pdf:

transcrypt_dev:
  hosts:
    agnt1:
      ansible_host: agn-t1.taxnet.ru
    agnt2:
      ansible_host: agn-t2.taxnet.ru
    dev_app:
      ansible_host: 192.168.170.33
    pre_app:
      ansible_host: 172.24.10.133
    stresstest_app:
      ansible_host: 172.24.10.62

transcrypt:
  children:
    transcrypt_prod:
    transcrypt_dev:
    tatenergosbyt:

veeam:
  hosts:
    veeam_itpark1:
      ansible_host: veeam-itpark.office.taxnet.ru
    veeam_itpark2:
      ansible_host: veeam-itpark-2.office.taxnet.ru
    veeam_itpark3:
      ansible_host: veeam-itpark-3.office.taxnet.ru
    veeam_kn:
      ansible_host: veeam-kn.office.taxnet.ru

taxnet:
  children:
    servers_1c:
    ad:
    backup_db:
    cryptogramm:
    cryptxdss:
    declaration:
    identify:
    infra:
    oktell:
    other:
    testenv:
    tfs:
    transcrypt:
    veeam: