_1c_group:
  hosts:
    1c8:
      ansible_host: srv1cv8.office.taxnet.ru
    1csql:
      ansible_host: 1csql.office.taxnet.ru
    summer3:
      ansible_host: summer3.office.taxnet.ru

ad_group:
  hosts:
    active:
      ansible_host: active.office.taxnet.ru
    bright:
      ansible_host: bright.office.taxnet.ru
    heaven:
      ansible_host: heaven.office.taxnet.ru

other_group:
  hosts:
    eufrat:
      ansible_host: eufrat.office.taxnet.ru

taxnet_nondomain:
  children:
    testenv_nondomain:
    tfs_nondomain:
    transcrypt:

taxnet_domain:
  children:
    _1c_group:
    ad_group:
    backupdb_group:
    cryptogramm:
    cryptxdss:
    declaration:
    identify_group:
    infra:
    oktell:
    other_group:
    tatenergosbyt:
    testenv_domain:
    tfs_domain:

disabled_hosts:
  hosts:
    veeam_kn:
    cryptogramm_gost:
    agn2:
    agnt1:
  children:
    identify_group:
    oktell:
    veeam:

taxnet:
  children:
    taxnet_domain:
    taxnet_nondomain:
    testenv:
    tfs:
    disabled_hosts: