other_group:
  hosts:
    eufrat:
      ansible_host: eufrat.office.taxnet.ru

taxnet_nondomain:
  children:
    testenv_nondomain:
    tfs_nondomain:
    transcrypt:

taxnet_domain:
  children:
    _1c_group:
    ad_group:
    backupdb_group:
    cryptogramm:
    cryptxdss:
    declaration:
    identify_group:
    infra:
    oktell:
    other_group:
    tatenergosbyt:
    testenv_domain:
    tfs_domain:

disabled_hosts:
  hosts:
    cryptogramm_gost:
    agn2:
    agnt1:
  children:
    identify_group:
    oktell:
    veeam:

taxnet:
  children:
    taxnet_domain:
    taxnet_nondomain:
    testenv:
    tfs:
    disabled_hosts:

taxnet_update1:
  children:
    transcrypt_update1:
    declaration_update1:
    tfs_update1:
    testenv:

taxnet_update2:
  children:
    transcrypt_update2:
    declaration_update2:
    tfs_update2:
    testenv:

taxnet_update:
  children:
    taxnet_update1:
    taxnet_update2: