---
rebacker:
  hosts:
    rebacker.office.taxnet.ru:
active:
  hosts:
    active.office.taxnet.ru:
bright:
  hosts:
    bright.office.taxnet.ru:
heaven:
  hosts:
    heaven.office.taxnet.ru:
narnia:
  hosts:
    narnia.office.taxnet.ru:

ad:
  children:
    active:
    bright:
    heaven:
  
backup:
  children:
    rebacker:

storage:
  children:
    narnia:

# mssql:
#   children:
#     rebacker:

# infra:
#   children:
#     rebacker:
#     narnia:
#     ad:
#     mssql:

taxnet:
  children:
    ad:
    backup:
    mssql:
    storage: