other_group:
  hosts:
    eufrat:
      ansible_host: eufrat.office.taxnet.ru

taxnet_nondomain:
  children:
    testenv_nondomain:
    tfs_nondomain:
    transcrypt:

taxnet_domain:
  children:
    _1c_group:
    ad_group:
    backupdb_group:
    cryptogramm:
    cryptxdss:
    declaration:
    identify_group:
    infra:
    oktell:
    other_group:
    tatenergosbyt:
    testenv_domain:
    tfs_domain:

disabled_hosts:
  hosts:
    cryptogramm_gost:
    agn2:
    agnt1:
  children:
    identify_group:
    oktell:
    veeam:

taxnet:
  children:
    taxnet_domain:
    taxnet_nondomain:
    testenv:
    tfs:
    disabled_hosts:

update_hosts1:
  hosts:
    demoreferent:
    webreferent_app:
    build_agent:
    obfuscator:
    dev_app:
  children:
    testenv:

updade_hosts2:
  hosts:
    flc:
    webreferent_sql:
    tfs_server:
    obfuscator:
    agnt2:
    pre_app:
  children:
    testenv:

updade_hosts:
  children:
    update_hosts1:
    updade_hosts2: