---

- name: Get Zabbix server version
  include_tasks: get_version.yml
  run_once: true
  when: 
    - zabbix_version | length == 0
    - zabbix_agent_version | length == 0

- debug:
    var: zabbix_version

- debug:
    var: zabbix_agent_version