---
- name: Set fact Zabbix version
  block:

    - name: Get Zabbix server version
      local_action: 
        module: ansible.builtin.uri
        url: "{{ zabbix_server_url }}"
        method: GET
        body_format: json
        src: version.json
      register: zabbix_server_version

    - name: Set fact Zabbix version 
      set_fact:
        zabbix_version_long: "{{ zabbix_server_version.json.result }}"
  
  when: zabbix_version_long | length == 0

- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family | lower }}.yml"

- name: Include OS-specific tasks 1
  include_tasks: "{{ ansible_os_family | lower }}3.yml"
  vars:
    zabbix_agent: agent1
    zabbix_agent_name: "{{ zabbix_agent_service[zabbix_agent] }}"

- name: Include OS-specific tasks 2
  include_tasks: "{{ ansible_os_family | lower }}3.yml"
  vars:
    zabbix_agent: agent2
    zabbix_agent_name: "{{ zabbix_agent_service[zabbix_agent] }}"