---
- name: "Windows | Set default architecture"
  set_fact:
    windows_arch: 32

- name: "Windows | Override architecture if 64-bit"
  set_fact:
    windows_arch: 64
  when:
    - ansible_architecture == "64-bit"