---
- name: "Windows | Check if Zabbix agent v1 is present"
  ansible.windows.win_stat:
    path: "{{ zabbix_agent_exe_path }}"
  register: zabbix_agent_info

- name: "Windows | Check if Zabbix agent v2 is present"
  ansible.windows.win_stat:
    path: "{{ zabbix_agent2_exe_path }}"
  register: zabbix_agent2_info

- name: "Windows | Get installed version Zabbix agent v1"
  community.windows.win_file_version:
    path: "{{ zabbix_agent_exe_path }}"
  register: zabbix_agent_file_version
  when: zabbix_agent_info.stat.exists

- name: "Windows | Get installed version Zabbix agent v2"
  community.windows.win_file_version:
    path: "{{ zabbix_agent2_exe_path }}"
  register: zabbix_agent2_file_version
  when: zabbix_agent2_info.stat.exists

- name: "Windows | Check Zabbix agent v1 service"
  ansible.windows.win_service:
    name: "{{ zabbix_agent_services.agent1 }}"
  register: zabbix_agent_service_info
  when: zabbix_agent_info.stat.exists

- name: "Windows | Check Zabbix agent v2 service"
  ansible.windows.win_service:
    name: "{{ zabbix_agent_services.agent2 }}"
  register: zabbix_agent2_service_info
  when: zabbix_agent2_info.stat.exists

- name: "Windows | Set fact about Zabbix agent v1 version change requirement"
  set_fact:
    zabbix_agent_version_change: true
  when:
    - zabbix_agent_file_version.win_file_version.product_version | default('empty') != zabbix_version_long

- name: "Windows | Set fact about Zabbix agent v2 version change requirement"
  set_fact:
    zabbix_agent2_version_change: true
  when: 
    - zabbix_agent2_file_version.win_file_version.product_version | default('empty') != zabbix_version_long

- block:

##################
# delete section #
##################

  - name: "Windows | Stop Zabbix agent v1"
    ansible.windows.win_service:
      name: "{{ zabbix_agent_services.agent1 }}"
      start_mode: auto
      state: stopped
    when:  zabbix_agent_service_info.exists | default(false)

  - name: "Windows | Stop Zabbix agent v2"
    ansible.windows.win_service:
      name: "{{ zabbix_agent_services.agent2 }}"
      start_mode: auto
      state: stopped
    when: zabbix_agent2_service_info.exists | default(false)

  - name: "Windows | Uninstall Zabbix agent v1"
    ansible.windows.win_command: "{{ zabbix_agent_uninstall_commands.agent1 }}"
    when: zabbix_agent_service_info.exists | default(false)

  - name: "Windows | Uninstall Zabbix agent v2"
    ansible.windows.win_command: "{{ zabbix_agent_uninstall_commands.agent2 }}"
    when: zabbix_agent2_service_info.exists | default(false)

###################
# install section #
###################

  - name: "Windows | Create directory structure"
    ansible.windows.win_file:
      path: "{{ zabbix_agent_install_dir }}"
      state: directory
    when: 
      - not zabbix_agent_info.stat.exists
      - not zabbix_agent2_info.stat.exists

  - name: "Windows | Check if Zabbix agent v1 zip package is already downloaded"
    ansible.windows.win_stat:
      path: "{{ zabbix_agent_zip_package }}"
    register: zabbix_agent_zip_package_info

  - name: "Windows | Check if Zabbix agent v2 zip package is already downloaded"
    ansible.windows.win_stat:
      path: "{{ zabbix_agent2_zip_package }}"
    register: zabbix_agent2_zip_package_info

  - name: "Windows | Download Zabbix Agent v1 Zip file"
    ansible.windows.win_get_url:
      url: "{{ zabbix_agent_download_link }}"
      dest: "{{ zabbix_agent_install_dir }}"
      force: false
    when: not zabbix_agent_zip_package_info.stat.exists
    register: zabbix_agent_download_zip

  - name: "Windows | Download Zabbix Agent v2 Zip file"
    ansible.windows.win_get_url:
      url: "{{ zabbix_agent2_download_link }}"
      dest: "{{ zabbix_agent_install_dir }}"
      force: false
    when: not zabbix_agent2_zip_package_info.stat.exists
    register: zabbix_agent2_download_zip

  - name: "Windows | Unzip Zabbix Agent v1 file"
    community.windows.win_unzip:
      src: "{{ zabbix_agent_zip_package }}"
      dest: "{{ zabbix_agent_install_dir }}"

  - name: "Windows | Unzip Zabbix Agent v2 file"
    community.windows.win_unzip:
      src: "{{ zabbix_agent2_zip_package }}"
      dest: "{{ zabbix_agent_install_dir }}"

  - name: "Windows | Cleanup downloaded Zabbix agent v1 Zip file"
    ansible.windows.win_file:
      path: '{{ zabbix_agent_zip_package }}'
      state: absent
    when:
      - zabbix_agent_download_zip.changed

  - name: "Windows | Cleanup downloaded Zabbix agent v2 Zip file"
    ansible.windows.win_file:
      path: '{{ zabbix_agent2_zip_package }}'
      state: absent
    when:
      - zabbix_agent2_download_zip.changed

  # Копировать шаблоны конфигов

  - name: "Windows | Check if windows service exist"
    ansible.windows.win_service:
      name: "{{ zabbix_agent_services[registration_zabbix_agent] }}"
    register: zabbix_agent_service

  - name: "Windows | Register {{ zabbix_agent_services[registration_zabbix_agent] }} service"
    ansible.windows.win_command: "{{ zabbix_agent_install_commands[registration_zabbix_agent] }}"
    when: not zabbix_agent_service.exists

  # - name: "Windows | Set service startup mode to auto, ensure it is started and set auto-recovery"
  #   ansible.windows.win_service:
  #     name: "{{ zabbix_win_svc_name }}"
  #     start_mode: auto
  #     failure_actions:
  #     - type: restart
  #       delay_ms: 5000
  #     - type: restart
  #       delay_ms: 10000
  #     - type: restart
  #       delay_ms: 20000
  #     failure_reset_period_sec: 86400

  when: >
    zabbix_agent_version_change | default(false)
    or
    zabbix_agent2_version_change | default(false)