- name: Windows | Install or Update Zabbix agent 1
  include_tasks: win_zabbix_agent.yml
  vars:
    zabbix_agent: agent1
    zabbix_agent_name: "{{ zabbix_agent_service[zabbix_agent] }}"

- name: Windows | Install or Update Zabbix agent 2
  include_tasks: win_zabbix_agent.yml
  vars:
    zabbix_agent: agent2
    zabbix_agent_name: "{{ zabbix_agent_service[zabbix_agent] }}"

- name: "Windows | Check firewall service"
  ansible.windows.win_service_info:
    name: MpsSvc
  register: firewall_info

- name: "Windows | Firewall rule"
  community.windows.win_firewall_rule:
    name: "{{ zabbix_firewall_name }}"
    group: "{{ zabbix_firewall_group }}"
    localport: "{{ zabbix_agent_listenport }}"
    action: allow
    direction: in
    protocol: tcp
    state: present
    enabled: true
  when:
    - firewall_info.services.state == 'started' or firewall_info.services.start_mode == 'auto'