veeam:
  hosts:
    veeam_itpark1:
      ansible_host: veeam-itpark.office.taxnet.ru
    veeam_itpark2:
      ansible_host: veeam-itpark-2.office.taxnet.ru
    veeam_itpark3:
      ansible_host: veeam-itpark-3.office.taxnet.ru
    veeam_kn:
      ansible_host: veeam-kn.office.taxnet.ru