cryptxdss_prod:
  hosts:
    copykey2:
      ansible_host: copykey2.office.taxnet.ru
    dssclients_clone:
      ansible_host: dssclientsclone.office.taxnet.ru
    dsstaxnet:
      ansible_host: dssup.office.taxnet.ru

cryptxdss_dev:
  hosts:
    copykey:
      ansible_host: copykey.office.taxnet.ru
    dsstaxnet_test:
      ansible_host: dss-taxnet-test.office.taxnet.ru
    dsstest:
      ansible_host: dsstest.office.taxnet.ru

cryptxdss:
  children:
    cryptxdss_prod:
    cryptxdss_dev: