cryptogramm_prod:
  hosts:
    cryptogramm_server:
      ansible_host: cryptogramm.office.taxnet.ru
    cryptogramm_gost:
      ansible_host: cryptogramm-gost.office.taxnet.ru
    rostselmash:
      # ansible_host: rostselmash.office.taxnet.ru
      ansible_host: 172.24.10.139

cryptogramm_dev:
  hosts:
    cryptogramm_demo:
      ansible_host: cryptogramm-demo.office.taxnet.ru
    rostselmash_test:
      ansible_host: rostselmash-test.office.taxnet.ru

cryptogramm:
  children:
    cryptogramm_prod:
    cryptogramm_dev: