declaration:
  hosts:
    demoreferent:
      ansible_host: demoreferent.office.taxnet.ru
    flc:
      ansible_host: flc.office.taxnet.ru
    webreferent_app:
      ansible_host: webreferent-app.office.taxnet.ru
    webreferent_sql:
      ansible_host: webreferent-sql.office.taxnet.ru