transcrypt_agn:
  hosts:
    agn1:
      ansible_host: 172.24.10.38

transcrypt_app:
  hosts:
    app_a:
      ansible_host: 172.24.10.53
    app_b:
      ansible_host: 172.24.10.122

transcrypt_pdf:
  hosts:
    pdf_a:
      ansible_host: 172.24.10.50
    pdf_b:
      ansible_host: 172.24.10.79

transcrypt_prod:
  children:
    transcrypt_agn:
    transcrypt_app:
    transcrypt_pdf:

transcrypt_dev:
  hosts:
    agnt2:
      ansible_host: 172.24.10.73
    dev_app:
      ansible_host: 192.168.170.33
    pre_app:
      ansible_host: 172.24.10.133
    stresstest_app:
      ansible_host: 172.24.10.62

transcrypt:
  children:
    transcrypt_prod:
    transcrypt_dev:


tatenergosbyt:
  hosts:
    tesb_eoks:
      ansible_host: tesb-eoks.office.taxnet.ru