---
- name: Pending reboot
  hosts: "{{ hostvar | default('nothing') }}:!disabled_hosts"
  gather_facts: false

  tasks:

    - name: Check the pending reboot
      ansible.windows.win_shell: "Test-PendingReboot -Detailed"
      register: pending_reboot
      changed_when: false

    - name: "Debug"
      ansible.builtin.debug:
        msg: "{{ pending_reboot.stdout_lines | select() | last }}"
      when: '"True" in pending_reboot.stdout_lines | select() | last'
      # vars:
      #   reboot_required: "{{ pending_reboot.stdout | trim | bool }}"
