---
- name: Checking and installing available updates
  hosts: "{{ hostvar | default('nothing') }}:!disabled_hosts"
  gather_facts: false
  vars:
    states:
      search: searched
      reboot: required
      install: installed
    playbook_state: "{{ states[state | default('search')] | default(states.search) }}"
    update_kb: KB890830

  tasks:

    - name: Check the pending reboot
      ansible.windows.win_shell: "(Test-PendingReboot).IsRebootPending"
      register: is_pending_reboot
      changed_when: false

    - name: Reboot the host if a reboot is required
      ansible.windows.win_reboot:
        reboot_timeout: 5400
      when:
        - playbook_state == states.install
        - is_pending_reboot.stdout | trim | bool

    - name: Delete the log file of the previous update installation
      ansible.windows.win_file:
        path: C:\ansible_wu.txt
        state: absent
      when:
        - playbook_state == states.install

    - name: Search for available updates
      ansible.windows.win_updates:
        state: searched
        category_names: '*'
        reject_list:
          - "{{ update_kb }}"
      register: available_updates

    - name: Installing available updates and reboot
      when: playbook_state == states.install
      block:

        - name: Installing available updates
          ansible.windows.win_updates:
            state: installed
            category_names: '*'
            accept_list: "{{ available_updates.updates | dict2items | json_query('[].value.kb') | flatten }}"
            log_path: C:\ansible_wu.txt
          register: installed_updates

        - name: Reboot the host if a reboot is required
          ansible.windows.win_reboot:
            reboot_timeout: 5400
          when: installed_updates.reboot_required


    - name: List of available or installed updates
      ansible.builtin.debug:
        msg: "{{ updades | json_query('[].value.title') | flatten | default('no updates') }}"
      vars:
        updades: "{{ (installed_updates.updates | default(available_updates.updates)) | dict2items }}"
