backupdb_group:
  hosts:
    rebacker:
      ansible_host: rebacker.office.taxnet.ru

infra:
  hosts:
    narnia:
      ansible_host: narnia.office.taxnet.ru
    naumen:
      ansible_host: Naumen.office.taxnet.ru
    rdgw:
      ansible_host: rdgw.office.taxnet.ru
    sus:
      ansible_host: sus.office.taxnet.ru
  children:
    backupdb_group: