testenv_domain:
  hosts:
    dpr_autotest:
      ansible_host: dpr-autotest.office.taxnet.ru
    win7testorispo:
      ansible_host: win7testorispo.office.taxnet.ru
    win7_dpr_test:
      ansible_host: win7-dpr-test.office.taxnet.ru
    
testenv_nondomain:
  hosts:
    w81x32_dpr:
      ansible_host: 192.168.170.40

testenv:
  children:
    testenv_domain:
    testenv_nondomain: