---
- name: Installing Windows update
  hosts: "{{ hostvar | default('nothing') }}:!disabled_hosts_group"
  gather_facts: false

  tasks:

    - name: Install all updates and reboot
      ansible.windows.win_updates:
        state: installed
        category_names: '*'
        reboot: true
        reboot_timeout: 1800
        log_path: C:\ansible_wu.txt
      # register: windows_updates

    # - name: "Debug"
    #   ansible.builtin.debug:
    #     var: windows_updates.updates[*].title
