---
- hosts: "{{ target_host }}"
  roles:
    - role: zabbix_agent
      zabbix_agent_force_change: true
      zabbix_server_fqdn: zabbix.taxnet.ru
      zabbix_server_url: "https://{{ zabbix_server_fqdn }}/zabbix/api_jsonrpc.php"
      zabbix_agent_hostmetadata:
        - "{{ (ansible_os_family == 'Windows') | ternary('WindowsActive', omit) }}"
        - "{{ 'mssql' in group_names | ternary('MSSQL', omit) }}"
        - "{{ 'transcrypt' in group_names | ternary('Transcrypt', omit) }}"
        - "{{ 'declaration' in group_names | ternary('Declaration', omit) }}"
