tfs_domain:
  hosts:
    tfs_server:
      ansible_host: tfs.office.taxnet.ru
    build_agent:
      ansible_host: dpr-build-agent.office.taxnet.ru
    
tfs_nondomain:
  hosts:
    obfuscator:
      ansible_host: 192.168.170.107

tfs:
  children:
    tfs_domain:
    tfs_nondomain: